version: '3.1'

services:

  pg:
    image: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: docker1234
    volumes:
      - pg-data:/var/lib/postgresql/data/

volumes:
  pg-data:
